CREATE TABLE notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    summary VARCHAR(500) NOT NULL,
    sections JSONB NOT NULL,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    published BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_notices_visible ON notices (published, pinned DESC, published_at DESC, id DESC);

CREATE TABLE inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    category VARCHAR(50) NOT NULL,
    subject VARCHAR(100) NOT NULL,
    body VARCHAR(2000) NOT NULL,
    related_session_id BIGINT,
    reply_email VARCHAR(254),
    status VARCHAR(20) NOT NULL CHECK (status IN ('RECEIVED', 'IN_PROGRESS', 'ANSWERED', 'CLOSED')),
    answer VARCHAR(4000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    answered_at TIMESTAMP WITH TIME ZONE,
    idempotency_key_sha256 VARCHAR(64),
    request_sha256 VARCHAR(64) NOT NULL,
    CONSTRAINT uq_inquiries_user_idempotency UNIQUE (user_id, idempotency_key_sha256)
);

CREATE INDEX idx_inquiries_user_created ON inquiries (user_id, created_at DESC, id DESC);
