ALTER TABLE users ADD COLUMN profile_image_url VARCHAR(2048);

CREATE TABLE profile_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    object_key VARCHAR(100) NOT NULL UNIQUE,
    image_url VARCHAR(2048) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
    key_digest VARCHAR(64),
    request_digest VARCHAR(64) NOT NULL,
    state VARCHAR(20) NOT NULL CHECK (state IN ('UPLOADING','ACTIVE','DELETE_PENDING','DELETED')),
    created_at TIMESTAMPTZ NOT NULL,
    activated_at TIMESTAMPTZ,
    cleanup_after TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_profile_images_user_key UNIQUE (user_id, key_digest)
);
CREATE UNIQUE INDEX uq_profile_images_active_user ON profile_images(user_id) WHERE state = 'ACTIVE';
CREATE INDEX idx_profile_images_cleanup ON profile_images(state, cleanup_after);
