CREATE TABLE title_policies (
    target_rank VARCHAR(30) PRIMARY KEY,
    required_training_count BIGINT NOT NULL CHECK (required_training_count >= 0),
    passing_score INTEGER NOT NULL CHECK (passing_score BETWEEN 0 AND 100),
    practice_content_id BIGINT REFERENCES practice_contents(id)
);
INSERT INTO title_policies(target_rank,required_training_count,passing_score) VALUES
    ('BEGINNER',5,70),('LOCAL_ANNOUNCER',15,75),('ASPIRING_ANNOUNCER',30,80),('ANNOUNCER',60,85);
CREATE TABLE user_titles (
    user_id BIGINT PRIMARY KEY REFERENCES users(id),
    rank VARCHAR(30) NOT NULL,
    minimum_training_count BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE title_exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    previous_rank VARCHAR(30) NOT NULL,
    target_rank VARCHAR(30) NOT NULL,
    practice_content_id BIGINT NOT NULL REFERENCES practice_contents(id),
    required_training_count BIGINT NOT NULL,
    passing_score INTEGER NOT NULL CHECK (passing_score BETWEEN 0 AND 100),
    training_session_id BIGINT UNIQUE,
    analysis_id BIGINT UNIQUE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('READY','IN_PROGRESS','PASSED','FAILED')),
    score NUMERIC(5,2),
    created_at TIMESTAMPTZ NOT NULL,
    evaluated_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_title_exam_active_target ON title_exams(user_id,target_rank) WHERE status IN ('READY','IN_PROGRESS');
CREATE TABLE title_exam_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    key_digest VARCHAR(64) NOT NULL,
    exam_id BIGINT NOT NULL REFERENCES title_exams(id),
    CONSTRAINT uq_title_exam_request UNIQUE(user_id,key_digest)
);
