CREATE TABLE course_step_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step_id BIGINT NOT NULL REFERENCES course_steps(id),
    revision INTEGER NOT NULL CHECK (revision > 0),
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(255),
    step_order INTEGER NOT NULL,
    step_type VARCHAR(50) NOT NULL,
    blocks_json TEXT NOT NULL CHECK (jsonb_typeof(blocks_json::jsonb) = 'array'),
    CONSTRAINT uq_course_step_revision UNIQUE(step_id, revision)
);

-- Copy only existing authored content. Do not invent diagrams, audio, or learning text.
INSERT INTO course_step_revisions(step_id,revision,title,step_order,step_type,blocks_json)
SELECT id,1,title,step_order,step_type,
    ((CASE WHEN body IS NOT NULL AND length(trim(body)) > 0
       THEN jsonb_build_array(jsonb_build_object('type','TEXT','body',body)) ELSE '[]'::jsonb END)
    || (CASE WHEN practice_content_id IS NOT NULL
       THEN jsonb_build_array(jsonb_build_object('type','PRACTICE_PROMPT','practiceContentId',practice_content_id))
       ELSE '[]'::jsonb END))::text
FROM course_steps;

ALTER TABLE training_sessions ADD COLUMN course_education_revision_id BIGINT REFERENCES course_step_revisions(id);
UPDATE training_sessions s SET course_education_revision_id = r.id
FROM course_step_revisions r WHERE s.course_step_id = r.step_id AND r.revision = 1;
CREATE INDEX idx_training_course_revision ON training_sessions(user_id,course_step_id,id DESC)
    WHERE course_education_revision_id IS NOT NULL;

-- Published revisions are append-only, including revisions retained by completed sessions.
CREATE FUNCTION prevent_course_revision_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Course education revisions are immutable; insert a new revision' USING ERRCODE = '23514';
END;
$$;
CREATE TRIGGER course_revision_immutable BEFORE UPDATE OR DELETE ON course_step_revisions
    FOR EACH ROW EXECUTE FUNCTION prevent_course_revision_mutation();
