ALTER TABLE practice_contents ADD COLUMN owner_id BIGINT REFERENCES users(id);
ALTER TABLE practice_contents ADD COLUMN custom_script_ciphertext TEXT;
ALTER TABLE practice_contents ADD COLUMN custom_title_ciphertext TEXT;
ALTER TABLE practice_contents ADD COLUMN custom_deleted_at TIMESTAMPTZ;
ALTER TABLE practice_contents ADD CONSTRAINT ck_private_content_visibility CHECK (owner_id IS NULL OR status='HIDDEN');
ALTER TABLE practice_contents ADD CONSTRAINT ck_private_content_storage CHECK (
    owner_id IS NULL OR (script_text='[private]' AND title='내 문장' AND
    ((custom_deleted_at IS NULL AND custom_script_ciphertext IS NOT NULL AND custom_title_ciphertext IS NOT NULL)
    OR (custom_deleted_at IS NOT NULL AND custom_script_ciphertext IS NULL AND custom_title_ciphertext IS NULL))));
CREATE INDEX idx_custom_content_owner ON practice_contents(owner_id) WHERE owner_id IS NOT NULL;
ALTER TABLE analysis_request_outbox ADD COLUMN private_payload_ciphertext TEXT;
CREATE TABLE custom_content_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    key_digest VARCHAR(64) NOT NULL,
    request_digest VARCHAR(64) NOT NULL,
    content_id BIGINT NOT NULL REFERENCES practice_contents(id),
    CONSTRAINT uq_custom_content_request UNIQUE(user_id,key_digest)
);
