ALTER TABLE practice_contents ADD COLUMN publisher VARCHAR(255);
ALTER TABLE practice_contents ADD COLUMN speaker_name VARCHAR(255);
CREATE TABLE content_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR(30) NOT NULL,
    code VARCHAR(100) NOT NULL,
    label VARCHAR(100) NOT NULL,
    sort_order INTEGER NOT NULL,
    CONSTRAINT uq_content_category UNIQUE(content_type,code)
);
-- Labels explicitly defined in the supplied API specification. Unknown codes remain unchanged.
INSERT INTO content_categories(content_type,code,label,sort_order) VALUES
    ('NEWS','SOCIETY','사회',1),('NEWS','ECONOMY','경제',2);
CREATE INDEX idx_content_catalog_order ON practice_contents(content_type,(CASE WHEN published_at IS NULL THEN 1 ELSE 0 END),published_at DESC,created_at DESC,id DESC)
    WHERE status='PUBLISHED' AND owner_id IS NULL;
