CREATE TABLE notification_preferences (
    user_id BIGINT PRIMARY KEY REFERENCES users(id),
    enabled BOOLEAN NOT NULL,
    reminder_time VARCHAR(5) NOT NULL,
    weekdays VARCHAR(27) NOT NULL,
    timezone VARCHAR(100) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE user_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    type VARCHAR(50) NOT NULL,
    title VARCHAR(200) NOT NULL,
    body VARCHAR(1000) NOT NULL,
    deep_link VARCHAR(255) NOT NULL CHECK (deep_link IN ('/home','/notifications','/mypage')),
    deduplication_key VARCHAR(100) NOT NULL,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_notification_event UNIQUE(user_id, deduplication_key)
);
CREATE INDEX idx_notification_inbox ON user_notifications(user_id, created_at DESC, id DESC);
CREATE INDEX idx_notification_unread ON user_notifications(user_id, created_at DESC, id DESC) WHERE read_at IS NULL;
CREATE INDEX idx_notification_reminders ON notification_preferences(user_id) WHERE enabled=true;
CREATE TABLE push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    endpoint_hash VARCHAR(64) NOT NULL UNIQUE,
    encrypted_payload TEXT NOT NULL,
    device_name VARCHAR(100),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_push_subscription_owner ON push_subscriptions(user_id);
CREATE TABLE push_registration_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    key_hash VARCHAR(64) NOT NULL,
    body_hash VARCHAR(64) NOT NULL,
    subscription_id BIGINT NOT NULL,
    device_name VARCHAR(100),
    subscription_created_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_push_registration_key UNIQUE(user_id,key_hash)
);
-- The request ledger intentionally survives subscription deletion to prevent replay resurrection.
