CREATE TABLE practice_example_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step_id BIGINT NOT NULL REFERENCES course_steps(id),
    revision INTEGER NOT NULL CHECK (revision>0),
    education_revision_id BIGINT NOT NULL REFERENCES course_step_revisions(id),
    published_at TIMESTAMPTZ NOT NULL,
    UNIQUE(step_id,revision), UNIQUE(id,revision)
);
CREATE TABLE practice_examples (
    id VARCHAR(100) PRIMARY KEY CHECK (id ~ '^[A-Za-z0-9_-]{1,100}$'),
    set_id BIGINT NOT NULL REFERENCES practice_example_sets(id),
    content_id BIGINT NOT NULL UNIQUE REFERENCES practice_contents(id),
    example_order INTEGER NOT NULL CHECK (example_order BETWEEN 1 AND 5),
    hint VARCHAR(500),
    focus VARCHAR(30),
    locale VARCHAR(10) NOT NULL CHECK(locale='ko-KR'),
    UNIQUE(set_id,example_order), UNIQUE(id,set_id,content_id)
);
ALTER TABLE training_sessions ADD COLUMN practice_example_id VARCHAR(100);
ALTER TABLE training_sessions ADD COLUMN practice_example_set_id BIGINT;
ALTER TABLE training_sessions ADD COLUMN practice_example_revision INTEGER;
ALTER TABLE training_sessions ADD CONSTRAINT fk_session_example FOREIGN KEY(practice_example_id,practice_example_set_id,content_id)
    REFERENCES practice_examples(id,set_id,content_id);
ALTER TABLE training_sessions ADD CONSTRAINT fk_session_example_revision FOREIGN KEY(practice_example_set_id,practice_example_revision)
    REFERENCES practice_example_sets(id,revision);
ALTER TABLE training_sessions ADD CONSTRAINT ck_session_example_pin CHECK (
    (practice_example_id IS NULL AND practice_example_set_id IS NULL AND practice_example_revision IS NULL)
    OR (practice_example_id IS NOT NULL AND practice_example_set_id IS NOT NULL AND practice_example_revision IS NOT NULL));
ALTER TABLE title_exams ADD COLUMN practice_example_set_id BIGINT;
ALTER TABLE title_exams ADD COLUMN practice_example_revision INTEGER;
ALTER TABLE title_exams ADD CONSTRAINT fk_exam_example_revision FOREIGN KEY(practice_example_set_id,practice_example_revision)
    REFERENCES practice_example_sets(id,revision);
ALTER TABLE title_exams ADD CONSTRAINT ck_exam_example_pin CHECK ((practice_example_set_id IS NULL)=(practice_example_revision IS NULL));
CREATE INDEX idx_session_example_revision ON training_sessions(user_id,course_step_id,id DESC) WHERE practice_example_set_id IS NOT NULL;
CREATE TABLE example_audio_cache (
    id VARCHAR(64) PRIMARY KEY,
    lease VARCHAR(36),
    lease_until TIMESTAMPTZ,
    audio BYTEA CHECK (audio IS NULL OR octet_length(audio) BETWEEN 3 AND 2000000),
    etag VARCHAR(66),
    CHECK ((audio IS NULL)=(etag IS NULL))
);
CREATE TABLE example_tts_quotas (
    id BIGINT PRIMARY KEY,
    window_minute BIGINT NOT NULL,
    attempts INTEGER NOT NULL
);
INSERT INTO example_tts_quotas VALUES(0,0,0);

CREATE FUNCTION validate_practice_example_set() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE target BIGINT;
BEGIN
    IF TG_TABLE_NAME='practice_example_sets' THEN target := NEW.id; ELSE target := NEW.set_id; END IF;
    IF (SELECT count(*) FROM practice_examples WHERE set_id=target)<>5 THEN
        RAISE EXCEPTION 'A published example revision requires exactly five items' USING ERRCODE='23514';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM practice_example_sets s JOIN course_step_revisions r ON r.id=s.education_revision_id AND r.step_id=s.step_id WHERE s.id=target) THEN
        RAISE EXCEPTION 'Example and education step mismatch' USING ERRCODE='23514';
    END IF;
    IF EXISTS (SELECT 1 FROM practice_examples e JOIN practice_contents c ON c.id=e.content_id WHERE e.set_id=target AND
        (c.owner_id IS NOT NULL OR c.content_type<>'CLASS_PRACTICE' OR c.status<>'PUBLISHED' OR length(trim(c.script_text))=0 OR octet_length(c.script_text)>4500)) THEN
        RAISE EXCEPTION 'Invalid published example content' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE CONSTRAINT TRIGGER example_set_complete AFTER INSERT ON practice_example_sets DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION validate_practice_example_set();
CREATE CONSTRAINT TRIGGER example_items_complete AFTER INSERT ON practice_examples DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION validate_practice_example_set();
CREATE TRIGGER example_set_immutable BEFORE UPDATE OR DELETE ON practice_example_sets
    FOR EACH ROW EXECUTE FUNCTION prevent_course_revision_mutation();
CREATE TRIGGER example_item_immutable BEFORE UPDATE OR DELETE ON practice_examples
    FOR EACH ROW EXECUTE FUNCTION prevent_course_revision_mutation();
CREATE FUNCTION prevent_example_content_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS(SELECT 1 FROM practice_examples WHERE content_id=OLD.id) AND
        (NEW.script_text IS DISTINCT FROM OLD.script_text OR NEW.title IS DISTINCT FROM OLD.title OR NEW.owner_id IS DISTINCT FROM OLD.owner_id
         OR NEW.content_type IS DISTINCT FROM OLD.content_type OR NEW.custom_script_ciphertext IS DISTINCT FROM OLD.custom_script_ciphertext OR NEW.custom_title_ciphertext IS DISTINCT FROM OLD.custom_title_ciphertext) THEN
        RAISE EXCEPTION 'Example content is immutable; publish a new revision' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER example_content_immutable BEFORE UPDATE ON practice_contents FOR EACH ROW EXECUTE FUNCTION prevent_example_content_mutation();
-- No fabricated lesson text or audio is inserted by this migration.
