CREATE TABLE example_tts_profiles (
    revision VARCHAR(120) PRIMARY KEY,
    fingerprint VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE example_tts_outbox (
    example_id VARCHAR(100) PRIMARY KEY REFERENCES practice_examples(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at TIMESTAMPTZ
);
CREATE TABLE example_tts_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    example_id VARCHAR(100) NOT NULL REFERENCES practice_examples(id),
    profile_revision VARCHAR(120) NOT NULL REFERENCES example_tts_profiles(revision),
    state VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK(state IN ('PENDING','RUNNING','RETRY_WAIT','GENERATED','FAILED')),
    attempt INTEGER NOT NULL DEFAULT 0 CHECK(attempt BETWEEN 0 AND 5),
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    lease_owner UUID,
    lease_until TIMESTAMPTZ,
    cache_key VARCHAR(64) REFERENCES example_audio_cache(id),
    audio_sha256 VARCHAR(64),
    duration_ms INTEGER,
    last_error_code VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(example_id,profile_revision),
    CHECK((state='RUNNING')=(lease_owner IS NOT NULL AND lease_until IS NOT NULL)),
    CHECK(state<>'GENERATED' OR (cache_key IS NOT NULL AND audio_sha256 IS NOT NULL AND duration_ms>0))
);
CREATE INDEX idx_example_tts_pending ON example_tts_jobs(profile_revision,next_attempt_at) WHERE state IN ('PENDING','RETRY_WAIT','RUNNING');
CREATE TABLE example_audio_approvals (
    job_id BIGINT NOT NULL REFERENCES example_tts_jobs(id),
    audio_sha256 VARCHAR(64) NOT NULL,
    reviewer_id VARCHAR(120) NOT NULL CHECK(length(trim(reviewer_id))>0),
    decision VARCHAR(10) NOT NULL CHECK(decision IN ('APPROVED','REJECTED')),
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY(job_id,reviewer_id)
);
CREATE FUNCTION enqueue_example_tts() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO example_tts_outbox(example_id) VALUES(NEW.id) ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$$;
CREATE TRIGGER example_tts_created AFTER INSERT ON practice_examples FOR EACH ROW EXECUTE FUNCTION enqueue_example_tts();
INSERT INTO example_tts_outbox(example_id) SELECT id FROM practice_examples ON CONFLICT DO NOTHING;
